### ISSUE TITLE
No such log file Exception

### ISSUE THREAD

**Issue by abordage** [stepanenko3/nova-logs-tool#6]
The package makes it possible to delete the log file, but at the same time, it throws an exception if the log is not found.

```php
if (!File::exists($file)) {
    throw new Exception('No such log file');
}
```

I suggest not throwing an exception.

**Comment by stepanenko3** [comment]
@abordage Thanks for issue

I'll consider it in the next few days

**Comment by stepanenko3** [comment]
@abordage fixed in [v2.0](https://github.com/stepanenko3/nova-logs-tool/releases/tag/v2.0.0)

**Comment by abordage** [comment]
version 2.0 - not fixed. If you delete all log files - an error appears:
```
Attempt to read property "name" on null { ... ErrorException(code: 0): Attempt to read property \"name\" on null at ... \\stepanenko3\\nova-logs-tool\\src\\Http\\Controllers\\LogsController.php:42)
```

**Comment by stepanenko3** [comment]
@abordage,

I'll consider it within a few days
